## PyTorch Quiz 4 : 텐서의 조작

In [1]:
import torch

### 문제1
- 2차원 텐서 [[1, 2, 3], [4, 5, 6]]를 3x2 텐서로 변환해서 출력하세요.

In [28]:
t1 = torch.tensor( [[1, 2, 3], [4, 5, 6]])
result1 =  t1.view(3,2)
print(result1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### 문제2
- 단일 값 텐서 tensor(42)에서 값을 추출하고 데이터 타입을 확인해서 출력하세요.

In [5]:
t2 = torch.tensor(42)
# (1) 값을 추출하고
print(t2.item())
# (2) 데이터 타입을 확인하세요.
print(t2.dtype)

42
torch.int64


### 문제 3
- 3차원 텐서 [[[1, 2, 3]]]에서 크기가 1인 차원을 제거해서 출력하세요.

In [32]:
t3 = torch.tensor([[[1,2,3]]])
print(t3.shape)
result3 = torch.squeeze(t3)
print(result3)
print(result3.shape)

torch.Size([1, 1, 3])
tensor([1, 2, 3])
torch.Size([3])


### 문제 4
- 1차원 텐서 [1, 2, 3]에 새로운 차원을 추가하여 2차원 텐서로 만들어 출력하세요.

In [34]:
t4 = torch.tensor([1,2,3])
result4 = torch.unsqueeze(t4, dim=0)
print(result4)
print(result4.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])


### 문제 5
- 두 텐서 a = [1, 2]와 b = [3, 4]를 쌓아 2x2 텐서를 생성해서 출력하세요.


In [10]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])
t5 = torch.stack([a,b])
print(t5)

tensor([[1, 2],
        [3, 4]])


### 문제 6
- 두 텐서 a = [[1, 2], [3, 4]]와 b = [[5, 6], [7, 8]]를 열 방향으로 연결해서 출력하세요.

In [14]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
t6 = torch.cat((a,b), dim=1)
print(t6)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### 문제 7
- 텐서 [[1, 2, 3], [4, 5, 6]]를 2개의 조각으로 나눠서 출력해보세요. (행 기준).

In [16]:
t7 = torch.tensor([[1,2,3],[4,5,6]])
t7_1, t7_2= torch.chunk(t7, 2)
print(t7_1, t7_2)

tensor([[1, 2, 3]]) tensor([[4, 5, 6]])


### 문제8
- 텐서 [1, 2, 3, 4, 5]를 각각 2, 2, 1의 크기로 나눠서 출력해보세요.

In [20]:
t8 = torch.tensor([1,2,3,4,5])
t8_1, t8_2, t8_3 = torch.split(t8, [2,2,1])
print(t8_1, t8_2, t8_3)

tensor([1, 2]) tensor([3, 4]) tensor([5])


### 문제9
- 텐서 [[1, 2], [3, 4], [5, 6]]에서:
- dim=1 기준으로 크기 1씩 나누세요.
- 각각의 조각을 새로운 축에 쌓은 후 출력해보세요.

In [36]:
t9 = torch.tensor([[1,2],[3,4],[5,6]])
# 1. 열 기준으로 크기 1씩 나누기
t9_1 = torch.split(t9, 1, dim=1)
print(t9_1)
# 2. 새로운 축에 쌓기
result9 = torch.stack(t9_1)
print(result9)

(tensor([[1],
        [3],
        [5]]), tensor([[2],
        [4],
        [6]]))
tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])


### 문제10
- 다음 텐서를 활용해서 아래 문제를 해결해보세요
  ```
  a = torch.tensor([[1, 2], [3, 4]])
  b = torch.tensor([[5, 6], [7, 8]])
  ```

1. 두 텐서를 열 기준으로 연결하고 결과를 출력하세요.
2. 연결된 텐서를 크기 `(4, 2)`로 변환하세요.
3. 변환된 텐서를 2개의 조각으로 나누고, 각 조각을 0번 축으로 스택하여 출력하세요.


In [38]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
# 1. 열 기준으로 병합
t10_1 = torch.cat((a,b),dim=1)
print(t10_1)
# 2. 크기 (4, 2)로 변환
t10_2 = t10_1.view(4,2)
print(t10_2)
# 3. 2개의 조각으로 나누고
t10_3 = torch.chunk(t10_2, 2)
print(t10_3)
# 4. 0번 축으로 스택
result10 = torch.stack(t10_3)
print(result10)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [5, 6],
        [3, 4],
        [7, 8]])
(tensor([[1, 2],
        [5, 6]]), tensor([[3, 4],
        [7, 8]]))
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
