## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
t1 = torch.tensor([2,4,6])
add = torch.add(t1, 5)
sub = torch.sub(t1, 3)
print("더하기", add)
print("빼기",sub)

tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [10]:
x = torch.rand(3,3)
y = torch.randn(3,3)

add = torch.add(x,y)
sub = torch.sub(x,y)
mul = torch.mul(x,y)
div = torch.div(x,y)

print("x", x)
print("y", y)
print("더하기", add)
print("빼기",sub)
print("곱하기", mul)
print("나누기", div)

x tensor([[0.6022, 0.9274, 0.9383],
        [0.4986, 0.0762, 0.5947],
        [0.7108, 0.2629, 0.8784]])
y tensor([[ 0.7418,  1.1895,  1.5196],
        [ 0.1951,  0.9883, -0.0695],
        [ 0.0446,  0.5595, -1.5167]])
더하기 tensor([[ 1.3441,  2.1169,  2.4579],
        [ 0.6937,  1.0645,  0.5251],
        [ 0.7555,  0.8224, -0.6382]])
빼기 tensor([[-0.1396, -0.2620, -0.5813],
        [ 0.3035, -0.9120,  0.6642],
        [ 0.6662, -0.2965,  2.3951]])
곱하기 tensor([[ 0.4468,  1.1032,  1.4259],
        [ 0.0973,  0.0753, -0.0413],
        [ 0.0317,  0.1471, -1.3323]])
나누기 tensor([[ 0.8118,  0.7797,  0.6175],
        [ 2.5555,  0.0771, -8.5551],
        [15.9342,  0.4700, -0.5792]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [7]:
tA = torch.tensor([[1,2,3], [4,5,6]])
tB = torch.tensor([[7,8],[9,10],[11,12]])

print(torch.matmul(tA, tB))

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [12]:
R = torch.tensor([[58, 64], [139, 154]])
R.add_(10)
print(torch.clamp(R, 0, 100))

tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [9]:
tM = torch.tensor([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])
print(torch.sum(tM, dim=0))

tensor([55, 60, 65, 70, 75])
