## 02. 텐서의 **연산**

In [2]:
import torch

### 2-1. 산술연산

In [6]:
x = torch.ones(2,2)
print(x)
x = x * 2
print(x)
x = x + 3
print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[5., 5.],
        [5., 5.]])


In [12]:
# 연산의 결과가 원본을 변경하지는 않음

x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[4,3],[2,1]])

# 더하기
add = torch.add(x, y)
print("더하기")
print(add)
print(x+y)

# 빼기
sub = torch.sub(x, y)
print("빼기")
print(sub)
print(x-y)

# 곱하기
mul = torch.mul(x, y)
print("곱하기")
print(mul)
print(x*y)

# 나누기
div = torch.div(x, y)
print("나누기")
print(div)
print(x/y)


더하기
tensor([[5, 5],
        [5, 5]])
tensor([[5, 5],
        [5, 5]])
빼기
tensor([[-3, -1],
        [ 1,  3]])
tensor([[-3, -1],
        [ 1,  3]])
곱하기
tensor([[4, 6],
        [6, 4]])
tensor([[4, 6],
        [6, 4]])
나누기
tensor([[0.2500, 0.6667],
        [1.5000, 4.0000]])
tensor([[0.2500, 0.6667],
        [1.5000, 4.0000]])
