## 03. 텐서의 조작

In [1]:
import torch

### 3-1. 인덱싱, 슬라이싱
- NumPy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [ ]:
x = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(x[1,1])
print(x[2,0])
print(x[0,:])   # 0행 전체
print(x[:,2])   # 2열 전체
print(x[[0,1,2],[0,1,2]])   # fancy indexing
print(x[x>5])   # boolean indexing

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [ ]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


### 3-2. 텐서의 크기, 모양 변경
- `torch.view()`

In [14]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = y.view(5, -1)   # -1 -> 자동 계산
print(z)

tensor([[-0.8578, -0.3813,  2.1046,  0.6889, -0.7363],
        [-1.3594, -0.6031,  0.2960, -0.6102, -0.7965],
        [ 0.8162,  0.2322,  0.4356, -0.5500,  0.8381],
        [ 0.8179, -0.0028, -1.7881,  1.3005,  0.9903]])
tensor([-0.8578, -0.3813,  2.1046,  0.6889, -0.7363, -1.3594, -0.6031,  0.2960,
        -0.6102, -0.7965,  0.8162,  0.2322,  0.4356, -0.5500,  0.8381,  0.8179,
        -0.0028, -1.7881,  1.3005,  0.9903])
tensor([[-0.8578, -0.3813,  2.1046,  0.6889],
        [-0.7363, -1.3594, -0.6031,  0.2960],
        [-0.6102, -0.7965,  0.8162,  0.2322],
        [ 0.4356, -0.5500,  0.8381,  0.8179],
        [-0.0028, -1.7881,  1.3005,  0.9903]])


### 3-3. 텐서의 숫자값 얻기
- `tensor.item()` : 스칼라 값 하나만 존재해야 사용 가능

In [ ]:
x = torch.rand(1)
print(x)
print(x[0])
print(x.item())

tensor([0.7903])
tensor(0.7903)
0.7902902960777283


### 3-4. 차원 축소 및 증가

#### 차원 축소(제거)
- `torch.squeeze()` : 크기가 1인 차원을 제거

In [17]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.1845, 0.0785, 0.3545]],

        [[0.9480, 0.7072, 0.7251]],

        [[0.7180, 0.5341, 0.5407]]])
torch.Size([3, 1, 3])
tensor([[0.1845, 0.0785, 0.3545],
        [0.9480, 0.7072, 0.7251],
        [0.7180, 0.5341, 0.5407]])
torch.Size([3, 3])


#### 차원 증가(생성)
- `torch.unsqueeze()` : dim 설정에 따라 차원을 증가시킴

In [21]:
t = torch.rand(3,3,3)
print(t)
print(t.shape)

ts1 = torch.unsqueeze(t, dim=0)
print(ts1)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
print(ts2)
print(ts2.shape)

tensor([[[0.8039, 0.2665, 0.3392],
         [0.8109, 0.6362, 0.5942],
         [0.0584, 0.3617, 0.8976]],

        [[0.3862, 0.6349, 0.8777],
         [0.5903, 0.5702, 0.1722],
         [0.9476, 0.3991, 0.5919]],

        [[0.8191, 0.4219, 0.5202],
         [0.2357, 0.7142, 0.2514],
         [0.3292, 0.2830, 0.6267]]])
torch.Size([3, 3, 3])
tensor([[[[0.8039, 0.2665, 0.3392],
          [0.8109, 0.6362, 0.5942],
          [0.0584, 0.3617, 0.8976]],

         [[0.3862, 0.6349, 0.8777],
          [0.5903, 0.5702, 0.1722],
          [0.9476, 0.3991, 0.5919]],

         [[0.8191, 0.4219, 0.5202],
          [0.2357, 0.7142, 0.2514],
          [0.3292, 0.2830, 0.6267]]]])
torch.Size([1, 3, 3, 3])
tensor([[[[0.8039, 0.2665, 0.3392],
          [0.8109, 0.6362, 0.5942],
          [0.0584, 0.3617, 0.8976]]],


        [[[0.3862, 0.6349, 0.8777],
          [0.5903, 0.5702, 0.1722],
          [0.9476, 0.3991, 0.5919]]],


        [[[0.8191, 0.4219, 0.5202],
          [0.2357, 0.7142, 0.2514],
     